name:                miso-template
version:             0.1

dependencies:
- base >= 4.7 && < 5
- miso
- jsaddle
- jsaddle-warp

library:
  source-dirs: src
  default-extensions:
  - RecordWildCards
  - OverloadedStrings

executables:
  miso-template-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    default-extensions:
    - RecordWildCards
    - OverloadedStrings
    dependencies:
    - miso-template

tests:
  miso-template-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miso-template
