name:                miso-template
version:             0.1

dependencies:
- base >= 4.7 && < 5
- miso
- jsaddle
- jsaddle-warp
- clay
- text
- containers
- lens

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  ghc-options:
  - -F -pgmF=record-dot-preprocessor

executables:
  miso-template-exe:
    main:                Main.hs
    source-dirs:         src
    default-extensions:
    - OverloadedStrings
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -F -pgmF=record-dot-preprocessor
    - -Wall
    - -Wno-name-shadowing
    dependencies:
    - miso-template

tests:
  miso-template-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miso-template
